const TEXT_TABLE_KEY_ADD_MEMO_SUCCESS = "ACTION_ADD_MEMO_SUCCESS";
const TEXT_TABLE_KEY_REMOVE_MEMO_EMPTY = "ACTION_REMOVE_MEMO_EMPTY";
const TEXT_TABLE_KEY_REMOVE_MEMO_INVALID_NUMBER = "ACTION_REMOVE_MEMO_INVALID_NUMBER";
const TEXT_TABLE_KEY_REMOVE_MEMO_SUCCESS = "ACTION_REMOVE_MEMO_SUCCESS";
const TEXT_TABLE_KEY_MODIFY_MEMO_EMPTY = "ACTION_MODIFY_MEMO_EMPTY";
const TEXT_TABLE_KEY_MODIFY_MEMO_INVALID_NUMBER = "ACTION_MODIFY_MEMO_INVALID_NUMBER";
const TEXT_TABLE_KEY_MODIFY_MEMO_SUCCESS = "ACTION_MODIFY_MEMO_SUCCESS";
const TEXT_TABLE_KEY_GET_MEMO_EMPTY = "ACTION_GET_MEMO_EMPTY";
const TEXT_TABLE_KEY_GET_MEMO_SUCCESS = "ACTION_GET_MEMO_SUCCESS";
const TEXT_TABLE_KEY_ADD_SCHEDULE_INVALID_KEY = "ACTION_ADD_SCHEDULE_INVALID_KEY";
const TEXT_TABLE_KEY_ADD_SCHEDULE_INVALID_TIME_RANGE = "ACTION_ADD_SCHEDULE_INVALID_TIME_RANGE";
const TEXT_TABLE_KEY_ADD_SCHEDULE_SUCCESS = "ACTION_ADD_SCHEDULE_SUCCESS";
const TEXT_TABLE_KEY_REMOVE_SCHEDULE_EMPTY = "ACTION_REMOVE_SCHEDULE_EMPTY";
const TEXT_TABLE_KEY_REMOVE_SCHEDULE_INVALID_NUMBER = "ACTION_REMOVE_SCHEDULE_INVALID_NUMBER";
const TEXT_TABLE_KEY_REMOVE_SCHEDULE_SUCCESS = "ACTION_REMOVE_SCHEDULE_SUCCESS";
const TEXT_TABLE_KEY_MODIFY_SCHEDULE_EMPTY = "ACTION_MODIFY_SCHEDULE_EMPTY";
const TEXT_TABLE_KEY_MODIFY_SCHEDULE_INVALID_NUMBER = "ACTION_MODIFY_SCHEDULE_INVALID_NUMBER";
const TEXT_TABLE_KEY_MODIFY_SCHEDULE_INVALID_KEY = "ACTION_MODIFY_SCHEDULE_INVALID_KEY";
const TEXT_TABLE_KEY_MODIFY_SCHEDULE_INVALID_TIME_RANGE = "ACTION_MODIFY_SCHEDULE_INVALID_TIME_RANGE";
const TEXT_TABLE_KEY_MODIFY_SCHEDULE_SUCCESS = "ACTION_MODIFY_SCHEDULE_SUCCESS";
const TEXT_TABLE_KEY_GET_SCHEDULE_EMPTY = "ACTION_GET_SCHEDULE_EMPTY";
const TEXT_TABLE_KEY_GET_SCHEDULE_SUCCESS = "ACTION_GET_SCHEDULE_SUCCESS";
const TEXT_TABLE_KEY_BUY_SUCCESS = "ACTION_BUY_SUCCESS";
const TEXT_TABLE_KEY_ACCOUNTING_DAILY_TOTAL = "ACCOUNTING_DAILY_TOTAL";
const TEXT_TABLE_KEY_ACCOUNTING_MONTHLY_TOTAL = "ACCOUNTING_MONTHLY_TOTAL";
const TEXT_TABLE_KEY_RECORD_BABY_DIAPER_CHANGING_TIME = "ACTION_RECORD_BABY_DIAPER_CHANGING_TIME";
const TEXT_TABLE_KEY_RECORD_BABY_EAT_TIME = "ACTION_RECORD_BABY_EAT_TIME";
const TEXT_TABLE_KEY_GET_CHART_COMMAND_INVALID = "ACTION_GET_CHART_COMMAND_INVALID"
const TEXT_TABLE_KEY_GET_CHART_COMMAND_EMPTY_ACCOUNT_CHART = "ACTION_GET_CHART_COMMAND_EMPTY_ACCOUNT_CHART"
const TEXT_TABLE_KEY_GET_CHART_COMMAND_EMPTY_DATA_SOURCE = "ACTION_GET_CHART_COMMAND_EMPTY_DATA_SOURCE"
const TEXT_TABLE_KEY_GET_CHART_ACCOUNT_PIE_CHART_TITLE_FORMAT = "ACTION_GET_CHART_ACCOUNT_PIE_CHART_TITLE_FORMAT"

//取得字表的值
function GetTextTableValue(searchKey) {
  var cell = GetSearchCellFromColumn(SHEET_NAME_TEXT_TABLE, searchKey);
  if(CheckCellIsNull(cell))
    return '';
  else
    return cell.getNextDataCell(SpreadsheetApp.Direction.NEXT).getValue();
}